# Prompt https://starship.rs/config/#prompt
format = "$all$character"
right_format = "$time"
scan_timeout = 500
command_timeout = 1_000

# AWS https://starship.rs/config/#aws
[aws]
disabled = true

# Battery https://starship.rs/config/#battery
[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

# Command Duration https://starship.rs/config/#command-duration
[cmd_duration]
min_time = 10_000

# Directory https://starship.rs/config/#directory
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"

# Google Cloud https://starship.rs/config/#google-cloud-gcloud
[gcloud]
disabled = true

# Git https://starship.rs/config/#git-status
[git_status]
conflicted = "ğŸ’¥"
ahead = "â©"
behind = "âª"
diverged = "ğŸ”¥"
up_to_date = "âœ¨"
untracked = "ğŸ†•"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "â™»ï¸"
deleted = "ğŸ—‘"

# Time https://starship.rs/config/#git-status
[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"
style = "white"
utc_time_offset = "+9"
